
set $laptop eDP-1
set $ibm DP-1

output $laptop scale 1.4

output $ibm mode 2560x1440@74.780Hz

# Disable laptop output if screen is closed.
bindswitch --reload --locked lid:on output $laptop disable
bindswitch --reload --locked lid:off output $laptop enable
