[style]
separator_block_width = 16

[icons]
theme = "nerdfont"

[[block]]
type = "github"
organization = "nos-digital"
token_file = "/home/tim/.config/bartender/github-token"
interval_seconds = 60

[[block]]
type = "memory"

[[block]]
type = "battery"

[[block]]
type = "clock"
format = "%Y-%m-%d %H:%M:%S"

